CREATE TABLE IF NOT EXISTS leads_sftp
(
    "ENTRYDATE" TEXT NOT NULL,
    "LEADNUMBER" TEXT NOT NULL,
    "email_hash" TEXT DEFAULT NULL,
    "phone_hash" TEXT DEFAULT NULL,
    "CITY" TEXT DEFAULT NULL,
    "STATE" TEXT DEFAULT NULL,
    "ZIP" TEXT DEFAULT NULL,
    "ApptDate" TEXT DEFAULT NULL,
    "Set" TEXT DEFAULT NULL,
    "Demo" TEXT DEFAULT NULL,
    "Dispo" TEXT DEFAULT NULL,
    "JobStatus" TEXT DEFAULT NULL,
    "location"  TEXT DEFAULT NULL,
    "loaded_at" TEXT DEFAULT NULL
);
